# INF8215 - Intelligence artif.: méthodes et algorithmes 
## Automne 2019 - TP3 - Apprentissage machine 
### Membres de l'équipe
    - Maude Nguyen-The (1843896)
    - Huyen Trang Dinh (1846776)

Nom d'équipe sur Kaggle: ln


## Directives de remise
Le travail sera réalisé avec la  même équipe que pour les TPs précédents. Vous remettrez ce fichier nommé TP3\_NomDuMembre1\_NomDuMembre2\_NomDuMembre3.ipynb et vos fichiers de soumission csv dans la boîte de remise sur moodle. 

Tout devra être remis avant le **13 décembre à 23h55**. Tout travail en retard sera pénalisé d’une valeur de 10\% par jour de retard.

## Barème
Partie 1: 9 points

Partie 2: 9 points

Partie 3: 2 points

Bonus : 2 points

Pour un total de 22 points possibles sur 20 points.


## Apprentissage machine
L'apprentissage machine est un domaine de plus en plus exploré et exploité. Pouvoir faire des prédictions en se basant sur des données ouvre la porte à plein de possibilités pour faciliter la vie des gens. Par exemple, un modèle pourrait prédire si un patient souffre ou non d'une maladie en se basant sur des mesures de santé.

### But
Le but de ce TP est de vous donner un aperçu du déroulement général d'un projet de machine learning tout en vous familiarisant avec des librairies python adaptées.

Dans la première partie, vous implémenterez un algorithme de classification multiclasse appelé **softmax regression** à l'aide uniquement de la bibliothèque **numpy** et l'intégrerez à la bibliothèque **scikit-learn**.

Dans la deuxième partie, vous prendrez connaissance du **dataset** utilisé pour ce projet. Et vous serez amenés à effectuer le **preprocessing** de ces données pour qu'elles soient utilisables dans les algorithmes de machine learning classiques. Vous utiliserez les bibliothèques **pandas** et **scikit-learn**.

Enfin, dans la troisième partie, vous comparerez l'efficacité du modèle que vous avez implémenté avec d'autres modèles déjà implémentés dans **sklearn**. Puis vous tenterez d'améliorer les performances de l'algorithme sélectionné.

La dernière partie du TP est de soumettre vos prédictions sur **Kaggle**. Vous devez créer un compte et formez une équipe sur Kaggle: https://www.kaggle.com/. La compétition pour le TP se trouve à l'adresse suivante: https://www.kaggle.com/t/7e5ae1ae92d14e06b2560c9ac5602bf6.

### Installation

Pour installer **pandas** et **scikit-learn** le plus simple est de télécharger et d'installer **Anaconda**. Cet environnement python regroupe les packages les plus utilisés pour le calcul scientifique et la science des données. Vous pouvez aussi installer directement les packages avec pip.

Assurez-vous d'avoir au moins la version **20.0** de **scikit-learn**.

Vous trouverez la distribution d'anaconda ici : https://www.anaconda.com/download/ .


## Bonus 1: Compétition (2 points)

Lorsque vous soumettez vos résultats sur Kaggle, vous obtiendrez votre performance en terme de **Mean F-Score**. Votre score sera affiché sur le leaderboard publique de Kaggle.  Le top 10 sur le leaderboard privée recevront un bonus de 2pts. Vous pouvez soumettre plusieurs fois et choisir 2 soumissions pour être pris en compte pour le classement final. Attention de ne pas overfit sur les données de tests du classement publique.

# 1. Softmax Regression (12 points)

Dans cette partie vous implémenterez **softmax regression** la généralisation de **logistic regression** qui permet d'effectuer de la classification pour un nombre de classe supérieur à 2.

**Pour cet exercice, la contrainte est d'utiliser uniquement la bibliothèque numpy**

## Encapsulation avec sklearn

La classe **SoftmaxClassifier** hérite des classes **BaseEstimator** et **ClassifierMixin** de **scikit-learn** ce qui nous permettra d'utiliser facilement avec notre classifier les outils fournis par scikit-learn dans la suite du TP.

Pour la compatibilité, le classifier doit implémenter obligatoirement les méthodes:

* **fit**: responsable de l'entraînement du modèle
* **predict_proba**: permet de prédire la probabilité de chaque classe pour chaque exemple du dataset fourni.
* **predict**: permet de prédire la classe pour chaque exemple du dataset fourni.
* **score**: permet de quantifier l'écart entre les classes prédites et les classes réelles pour le dataset fourni
* **fit_predict**: permet de faire un fit et retourne les prédictions faites avec cet ensemble.


## Train/Test set:

Quand on veut tester les performances de l'apprentissage d'un algorithme de machine learning, on **ne le teste pas sur les données utilisées pour l'apprentissage**.

En effet, ce qui nous intéresse c'est que notre algorithme soit **capable de généraliser** ses prédictions à des données qu'il n'a **jamais vu**.

Pour illustrer, si on teste un algorithme sur les données d'entrainement, on teste sa capacité à **apprendre par coeur** le dataset et non à **généraliser**.

Par conséquent, quand on reçoit un nouveau dataset, la première chose à faire et de le **diviser en deux parties**: un ensemble d'**entraînement** (**70-80%** du dataset) et un ensemble de **test**(**20-30%** du dataset).

Tous les algorithmes de **traitement des données** et d'apprentissage devront être appris uniquement sur l'ensemble d'entraînement et appliqués ensuite sur l'ensemble de test.

Cela garantit l'absence de connaissances préalables de l'ensemble de test lors de l'entrainement.

## Gradient descent

La descente de gradient est un algorithme qui permet trouver la solution optimale d'un certains nombre de problèmes. Le principe est le suivant: on définit une **fonction de coût J**  qui caractérise le problème.
Cette fonction dépend d'un ensemble de paramètres $\theta$. La descente de gradient cherche à **minimiser** la fonction de coût en **modifiant itérativement** les paramètres.

### Gradient

Le gradient de la fonction de coût pour un $\theta$ donné, correspond à la direction dans laquelle il faut modifier $\theta$ pour augmenter la valeur de la fonction de coût. Cela correspond donc à la dérivée de la fonction de coût.
La fonction de coût est minimale quand le gradient est nul.

Concrètement, on initialize $\theta$ aléatoirement, et on effectue à chaque itération un pas pour réduire la fonction de coût jusqu'à convergence de l'algorithme à un minimum.

### Learning rate

Le taux d'apprentissage correspond à la taille du pas que l'on va effectuer dans la direction du gradient.
Plus il est grand, plus la convergence est rapide mais il y a un risque que l'algorithme diverge.

Plus il est petit, plus la convergence est lente.

### Batch gradient descent

Il existe plusieurs algorithmes de descente de gradient. Nous utiliserons Batch gradient descent.

Dans cet algorithme, avant de mettre à jour $\theta$, on calcule les gradients sur l'ensemble des exemples d'entraînement.

### Epoch

Il s'agit d'un pas de la descente de gradient, soit une mise à jour de gradient.

### Bias/Variance tradeoff

Lorsqu'on entraine un algorithme de machine learning on cherche un équilibre entre **biais** et **variance**.

Un modèle avec un **biais fort**, est un modèle qui est **trop simple** pour la structure donnée considérée (modèle linéaire pour données quadratiques), cela limite la capacité du modèle à généraliser. On appelle aussi le biais **underfitting**.

Un modèle avec une **variance élevée** signifie qu'il est sensible aux petites variations dans les données d'entrainement, cela correspond à l'**overfitting**, c'est-à-dire que le modèle est trop proche de la structure de l'ensemble d'entrainement ce qui **limite sa capacité à généraliser**.

Un modèle avec un **biais important** aura une **mauvaise performance** sur l'ensemble d'**entraînement**.
Un modèle avec une **variance importante** aura une performance bien **moins bonne** sur l'ensemble de **test** que sur l'ensemble d'**entrainement**.

Le classifier **SoftmaxRegression** contient les champs suivants:

- `lr` : le rythme d'apprentissage pour la mise à jour des points lors de la descente du gradient;
- `n_epochs`: le nombre d'itérations;
- `eps`: le seuil pour garder les probabilités dans l'intervalle [self.eps;1.-self.eps];
- `threshold`: seuil d'arrèt pour le early stopping;
- `early_stopping`: active le early stopping
- `nb_features`: le nombre d'attributs pour chaque instance
- `nb_classes`: le nombre de classes possible pour le dataset
- `theta_`:  la matrice de poids

In [1]:
from sklearn.base import BaseEstimator, ClassifierMixin
import numpy as np


class SoftmaxClassifier(BaseEstimator, ClassifierMixin):  

    def __init__(self, lr = 0.1, alpha = 100, n_epochs = 1000, eps = 1.0e-5,threshold = 1.0e-10 , early_stopping = True):
       
        self.lr = lr 
        self.alpha = alpha
        self.n_epochs = n_epochs
        self.eps = eps
        self.threshold = threshold
        self.early_stopping = early_stopping
        


    """
        In:
        X : l'ensemble d'exemple de taille nb_example x nb_features
        y : l'ensemble d'étiquette de taille nb_example x 1

        Principe:
        Initialiser la matrice de poids
        Ajouter une colonne de bias à X
        Pour chaque epoch
            calculer les probabilités
            calculer le log loss
            calculer le gradient
            mettre à jouer les poids
            sauvegarder le loss
            tester pour early stopping

        Out:
        self, in sklearn the fit method returns the object itself
    """

    def fit(self, X, y=None):
        
        prev_loss = np.inf
        self.losses_ = []

        self.nb_feature = X.shape[1]
        self.nb_classes = len(np.unique(y))

        X_bias = np.concatenate((np.ones((X.shape[0],1)), X), axis=1)         
        self.theta_ = np.random.rand(self.nb_feature+1, self.nb_classes)
        

        for epoch in range( self.n_epochs):

            probabilities = self.predict_proba(X, y)
            
            
            loss = self._cost_function(probabilities, y)               
            self.theta_ = self.theta_ - self.lr*self._get_gradient(X_bias, y, probabilities)
            self.losses_.append(loss)

            if self.early_stopping:
                if len(self.losses_) > 1 and self.losses_[-2] - self.losses_[-1] < self.threshold:
                    return self


        return self


    def predict_proba(self, X, y=None):
        try:
            getattr(self, "theta_")
        except AttributeError:
            raise RuntimeError("You must train classifer before predicting data!")
        X_bias = np.concatenate((np.ones((X.shape[0],1)), X), axis=1) 
        return self._softmax(X_bias.dot(self.theta_))

    
    def predict(self, X, y=None):
        try:
            getattr(self, "theta_")
        except AttributeError:
            raise RuntimeError("You must train classifer before predicting data!")
        probs = self.predict_proba(X,y)
        return np.argmax(probs, axis=1)
        

    
    def fit_predict(self, X, y=None):
        self.fit(X, y)
        return self.predict(X,y)
 

    def score(self, X, y=None):
        probs = self.predict(X)
        return self._cost_function(probs, y)
    
    
    def _cost_function(self,probabilities, y ): 
        y = self._one_hot(y)
        np.clip(probabilities, self.eps, 1-self.eps)
        loss = y * np.log(probabilities)
        loss = loss.sum(axis=1)
        return (-1 / y.shape[0]) * loss.sum(axis=0)
        
    

    def _one_hot(self,y):
        one_hot = np.zeros((len(y), self.nb_classes))
        for i in range(len(y)):
            one_hot[i][y[i]] = 1
        return one_hot

    
    def _softmax(self,z):
        denom = np.sum(np.exp(z))
        return np.divide(np.exp(z), denom)


    def _get_gradient(self,X_bias,y, probas):
        return (np.transpose(X_bias).dot(probas - self._one_hot(y)))/len(y)
    
    

### 1.1 One-hot-encoding (1 point)

En machine learning pour représenter un vecteur de données catégoriques, on utilise le one-hot encoding.

Pour un vecteur comportant 5 exemples et 3 catégories différentes, on le représente sous forme d'une matrice de taille 5 par 3. Cette matrice est entièrement remplie de 0 sauf à l'indice correspondant au numéro de la classe pour chaque exemple.


Par exemple
$ y = \left(\begin{array}{cc} 
0 \\
0 \\
1 \\
2 \\
1 \\
\end{array}\right) $

devient:

$ yohe =  \left(\begin{array}{cc} 
1. & 0. & 0.\\
1. & 0. & 0.\\
0. & 1. & 0.\\
0. & 0. & 1.\\
0. & 1. & 0.\\
\end{array}\right) $


#### Implémentation
1. Implémentez  la fonction  *`_one_hot()`*  dans SoftmaxClassifier. 

Utilisez la fonction _testOneHot_ pour vérifier votre implémentation de la fonction. Vous devriez avoir ces résultats:
```
Premier test
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Deuxième test
[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]

 Troisième test
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
 ```

In [2]:
def testOneHot():
    softmax = SoftmaxClassifier()
    softmax.nb_classes = 6 # les classes possibles sont donc 0-5

    y1= np.array([0,1,2,3,4,5])
    y1.shape = (6,1)
    print('Premier test')
    print(softmax._one_hot(y1))

    y2 = np.array([5,5,5,5])
    y2.shape = (4,1)
    print('\nDeuxième test')
    print(softmax._one_hot(y2))

    y3 = np.array([0,0,0,0])
    y3.shape = (4,1)
    print('\nTroisième test')
    print(softmax._one_hot(y3))


testOneHot()

Premier test
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Deuxième test
[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]

Troisième test
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


### 1.2 Matrice de poids (1 point)

Soit $ X_{m * n} $ la matrice d'exemple et $ \Theta _{n*K} $ la matrice de poids avec:

* **m** le nombre d'exemples
* **n** le nombre de features
* **k** le nombre de classes

Il est d'usage d'ajouter une colonne supplémentaire à X. Cette colonne est remplie de 1 et se trouve au début de la matrice. Elle représente un biais. Pour prendre en compte ce changement, il faut aussi rajouter une ligne à la matrice $\Theta$.

On obtient X_bias$_{m*(n+1)}$ et $ \Theta _{(n+1)*K} $


Intuitivement, à chaque classe K est associée une colonne de $\theta$.

On note $\theta_k$ le vecteur de dimension n+1 la colonne de poids associée à la prédiction de la classe k.

$\Theta$ = [$\theta_0$,$\theta_1$... $\theta_k$]

Ainsi $ z = x * \Theta $ donne un vecteur de dimension K qui correspond aux **logits** associés à x pour chacune des classes.

#### Implémentation
1. Instanciez X_bias dans les fonctions  *`fit()`* et `predict_proba()`.
2. initialisez $\Theta$ aléatoirement dans la fonction  *`fit()`*.
3. Instanciez aussi le nombre de features et de classe de SoftmaxClassifier dans la fonction  *`fit()`*.

**Notez que votre fonction fit n'est pas encore complète.**

### 1.3 Softmax (1 point)

On veut convertir le vecteur de logits **z** obtenu dans la partie précédente, en un **vecteur de probabilité**.

Pour cela on définit la **fonction softmax**:

$$ \hat{p_x}^k = softmax(z)_k = \frac{exp(z_k)}{\sum_{\substack{1<j<K}} exp(z_j)} $$

Intuitivement, pour un logit de z, $z_k$, on prend l'exponentielle de cette valeur et on la divise par la somme des exponentielles de chaque logit du vecteur **z**. On obtient  $\hat{p_x}^k$ la probabilité que l'exemple **x** appartienne à la classe **k**.

On réitère l'opération pour chaque logit du vecteur **z**. 

On obtient ainsi un vecteur de probabilités $\hat{p_x}$ pour un exemple **x**. 

La division permet de rendre la somme des termes du vecteur $\hat{p_x}$ égale à 1 ce qui est indispensable dans le cadre des probabilités.

#### Implémentation
1. Implémentez  la fonction  *`_softmax()`*  dans SoftmaxClassifier. 

### 1.4 Prédictions (1 point)

Maintenant que vous avez implémentée la fonction **_softmax**, vous pouvez implémenter  les fonctions  **predict_proba** et **predict**  dans SoftmaxClassifier. 

#### Implémentation
1. Implémenter la fonction *`predict_proba()`* de la classe SoftmaxClassifier. Cette fonction retourne les probabilités associées à chaque classe pour chacune des instances à prédire.

2. Implémenter la fonction *`predict()`* de la classe SoftmaxClassifier. Cette fonction retourne la classe avec la plus grande probabilité pour chacunes des intances à prédire.

### 1.5 Fonction de coût Log loss (2 points)

Soit la fonction de coût log loss (ou cross entropy):

$$ J( \Theta) = \frac{-1}{m}\sum_{\substack{1<i<m}} \sum_{\substack{1<k<K}} y_k^i log( \hat{p_k}^i ) $$

avec:
* **K** le nombre de classes
* **m** le nombre d'exemples dans les données
* $ \hat{p_k}^i  $  la probabilité que l'exemple i soit de la classe k
* $y_k^i$ vaut 1 si la classe cible de l'exemple i est k, 0 sinon

Le coût correspond donc à la moyenne multiplié par -1 des sommes des multiplications des probabilités pour chaque classe pour chaque élement. Autrement dit, plus le coût est petit, plus les prédictions correspondent bien aux étiquettes.


**Détail d'implémentation:** La fonction n'est pas définie pour des valeurs de probabilité de 0 ou 1. Il faut donc s'assurer que étant donné $\epsilon$, les probabilités sont comprises dans [$\epsilon$, 1. - $\epsilon$].
#### Implémentation
1. Implémentez  la fonction  *`_cost_function()`*  dans SoftmaxClassifier en prenant en utilisant la variable self.eps. Utilisez le format one-hot pour représenter $y_k^i$.
2.  Utilisez *`_cost_function()`* pour calculer la variable *`loss`* dans la fonction `fit()`

### 1.6 Gradient de la fonction de coût (1 point)

Le **gradient de J** par rapport à la classe k (par rapport à $\theta_k$) est :


$$ \Delta_{\theta_k}J( \Theta) = \frac{1}{m} \sum_{\substack{1<i<m}}( \hat{p_k}^i - y_k^i)x^i  $$

avec:
* **K** le nombre de classes
* **m** le nombre d'exemples dans les données
* $ \hat{p_k}^i  $  la probabilité que l'exemple i soit de la classe k
* $y_k^i$ vaut 1 si la classe cible de l'exemple i est k, 0 sinon

Sous **forme matricielle**, on peut écrire le **gradient de J par rapport à $\Theta$**:
$$ \Delta_J( \Theta) = \frac{1}{m} X_{bias}^T *( \hat{p} - y_{ohe}) $$

avec:
* $\hat{p}$ la matrice de probabilité prédite pour chaque example et pour chaque classe
* $y_{ohe}$ la version one-hot de y
* $X_{bias}^T$  la matrice transposée de $X_{bias}$
* **\*** le produit matriciel

#### Implémentation
1. Implémentez  la fonction  *`_get_gradient()`*  dans SoftmaxClassifier en vous basant sur la forme matricielle du gradient.

### 1.7 Mise à jour des poids (1 point)

Quand le gradient a été calculé, il faut mettre à jour les poids avec ces gradients.

$$ \Theta  = \Theta - \gamma \Delta J( \Theta) $$


avec:
* $\Theta$ la matrice de poids
* $\gamma$  le taux d'apprentissage
* $\Delta J( \Theta)$ le gradient de $J( \Theta)$ selon $\Theta$

#### Implémentation
1. Mettez à jour la variable **self.theta_** dans la fonction `fit()`  dans SoftmaxClassifier.

### 1.8 Évaluation (1 point)

Quand on veut évaluer la performance du modèle **après entrainement**, on utilise la fonction de coût. Autrement dit, on compare les prédictions avec les vrais valeurs et calcule un score.

#### Implémentation
1. Implémentez la fonction `score()` qui permet d'évaluer la qualité de la prédiction **après entrainement** dans SoftmaxClassifier. Elle utilise le log loss comme métrique.

### 1.9 Early stopping (1 point)

Un trop grand nombre d'**epoch** peut résulter en **overfitting**.
Pour pallier à ce problème, on peut utiliser le mécanisme d'**early stopping**.
Il s'agit d'arrêter l'entraînement si la différence de la fonction de coût entre deux **epochs consécutives** est inférieure à un **seuil**.




#### Implémentation

1. Ajouter le mécanisme d'**early stopping**  quand le booléen **self.early_stopping** est vrai dans la fonction `fit()`. Le seuil est donné par la variable **self.threshold**.

### 1.10 Test de la solution (2 points)

Le code ci-dessous importe le dataset de classification multiclasse **iris** disponible sur sklearn. Les données sont divisées en deux parties, l'ensemble d'entraînement et l'ensemble de test, puis elles sont normalisées.

Le classifier est entrainé sur l'ensemble d'entrainement et testé sur l'ensemble de test.

Le but de cette partie est juste de vérifier votre implémentation **quand vous êtes sûrs que votre code fonctionne**.

In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# load dataset
data,target =load_iris().data,load_iris().target

# split data in train/test sets
X_train, X_test, y_train, y_test = train_test_split( data, target, test_size=0.33, random_state=42)

# standardize columns using normal distribution
# fit on X_train and not on X_test to avoid Data Leakage
s = StandardScaler()
X_train = s.fit_transform(X_train)
X_test = s.transform(X_test)

In [4]:
cl = SoftmaxClassifier()

# train on X_train and not on X_test to avoid overfitting
train_p = cl.fit_predict(X_train,y_train)
test_p = cl.predict(X_test)

Si vous obtenez des valeurs relativement proches pour l'ensemble de test et d'entrainement, et qu'elles sont au moins supérieures à 0.8, votre modèle devrait être correct

In [5]:
from sklearn.metrics import precision_recall_fscore_support

# display precision, recall and f1-score on train/test set
print("train : "+ str(precision_recall_fscore_support(y_train, train_p,average = "macro")))
print("test : "+ str(precision_recall_fscore_support(y_test, test_p,average = "macro")))

train : (0.8955857385398982, 0.8932773109243697, 0.8933614330874605, None)
test : (0.8067226890756304, 0.8055555555555555, 0.8056426332288401, None)


# 2. Data preprocessing (6 points)

##  Kaggle 
Kaggle est un site dédié au machine learning. On y retrouve un grand nombre de dataset.
Des compétitions sont organisées par des organisations. Ces dernières fournissent un dataset et un objectif. Les "kagglers" qui participent à ces compétitions soumettent leurs résultats en ligne. Il y a souvent des prix ou des emplois pour ceux qui obtiennent les meilleurs résultats.

Il s'agit d'un bon moyen pour développer ses compétences en machine learning sur des vrais datasets.

Vous devez créer un compte et formez une équipe sur Kaggle: https://www.kaggle.com/. La compétition pour le TP se trouve à l'adresse suivante: https://www.kaggle.com/c/tp3-inf8215-a19.


## Income dataset
Le dataset que nous utiliserons est le "Income dataset" disponible sur le site de la compétition. C'est une version modifiée du dataset "Adult" de UCI qui se trouve à cette adresse: https://archive.ics.uci.edu/ml/datasets/Adult.

Il s'agit d'un problème de **classification binaire** du salaire de la personne. Le but est de prédire dans quel catégorie ils appartiennent:
* $\lt=50K$
* $\gt50K$

Pour plus d'informations sur les données, lisez la description sur kaggle.

## Déroulement d'un projet de machine learning

Le but de la suite de ce TP est de vous faire étudier une version simplifiée d'un projet complet de machine learning:

1. Nettoyage des données, traitement des valeurs manquantes
2. Mise en forme des données pour pouvoir les utiliser dans les algorithmes de machine learning
3. Feature engineering: transformation ou combinaison de features entre elles
4. Comparaison des performances des différents choix effectués lors du traîtement des données
5. Comparaison des performances de différents modèles (dont celui implémenté en première partie)
6. Optimisation des hyper-paramètres

## Scikit-learn
http://scikit-learn.org/stable/

Il s'agit d'une bibliothèque de machine learning et data mining, elle propose des outils pour l'analyse et le traîtement des données,  des algorithmes classiques de machine learning comme les réseaux de neuronnes, la régression logistique, les SVM ou autre, enfin des outils permettant de comparer les modèles entre eux comme la cross validation.

## Pandas

Une bibliothèque permettant de stocker des données et de les manipuler facilement

Les deux éléments de base de pandas sont le dataframe et la serie.

https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.html

## Data processing tutorial

**Avant de continuer le TP**, familiarisez-vous avec le **pré-traitement des données**, **pandas** et **scikit-learn**, un tutoriel est disponible dans le fichier: **data_processing_tutorial.ipynb**

## Dataset

#### Chargement de l'ensemble d'entraînement et de l'ensemble de test

In [6]:
import pandas as pd

PATH = "data/" # changer le path avec votre path
X_train = pd.read_csv(PATH + "train.csv")
y_train = X_train['Income']
X_test = pd.read_csv(PATH + "test.csv")

#### 5 premiers exemples de l'ensemble d'entraînement

In [7]:
X_train.head()

index  Age      Workclass  Final weight   Education       Marital-status  \
0  36721   36        Private         31023     Masters   Married-civ-spouse   
1   2638   52              ?        159755   Assoc-voc   Married-civ-spouse   
2  36214   36        Private        359001   Assoc-voc             Divorced   
3  27010   42   Self-emp-inc        188615   Bachelors   Married-civ-spouse   
4  27506   44        Private         43711   Bachelors        Never-married   

         Occupation    Relationship    Sex  Capital-gain  Capital-loss  \
0   Exec-managerial         Husband   Male             0             0   
1                 ?         Husband   Male             0             0   
2      Craft-repair   Not-in-family   Male             0             0   
3             Sales         Husband   Male             0             0   
4     Other-service   Not-in-family   Male             0             0   

   Hours per week  Native country   Income  
0              50   United-States    >50K.  
1              50   United-States     >50K  
2              40   United-States   <=50K.  
3              60   United-States     >50K  
4              48   United-States    <=50K

#### 5 premiers exemples de l'ensemble de test

In [8]:
X_test.head()

index  Age   Workclass  Final weight      Education  Marital-status  \
0   7762   18     Private      423024.0        HS-grad   Never-married   
1  23881   17     Private      178953.0           12th   Never-married   
2  30507   25   Local-gov      348986.0        HS-grad   Never-married   
3  28911   20     Private      218215.0   Some-college   Never-married   
4  19484   47     Private      244025.0        HS-grad   Never-married   

           Occupation     Relationship      Sex  Capital-gain  Capital-loss  \
0       Other-service    Not-in-family     Male           0.0           0.0   
1               Sales        Own-child   Female           0.0           0.0   
2   Handlers-cleaners   Other-relative     Male           0.0           0.0   
3               Sales        Own-child   Female           0.0           0.0   
4   Machine-op-inspct        Unmarried     Male           0.0           0.0   

   Hours per week  Native country  
0            20.0   United-States  
1            20.0   United-States  
2            40.0   United-States  
3            30.0   United-States  
4            56.0     Puerto-Rico

#### 5 premiers exemples de l'attribut à prédire

In [9]:
y_train.head()

0      >50K.
1       >50K
2     <=50K.
3       >50K
4      <=50K
Name: Income, dtype: object

## Travail demandé

En vous appuyant sur le tutoriel fourni, vous devez écrire un pipeline complet de transformation pour chacune des colonnes du dataset.

Vous êtes **libres** de vos choix, mais vous devez les **justifer** colonne par colonne.
Par exemple, vous pouvez choisir de combiner des colonnes entre elles, de séparer une colonne en plusieurs ou encore d'éliminer complètement une colonne si vous le justifiez correctement.


####  2.1 Preprocessing (3 points)

Vous devez justifier toutes les transformations que vous faites sur les données pour faciliter l'utilisation des données lors de l'entraînement du modèle. Vous pouvez justifier avec de la logique ou des preuves numériques. **Attention de ne pas tomber dans le piège du overfitting**.

**ATTENTION** Vous devez avoir un meilleur score que le baseline pour le classement privé pour avoir votre point au complet pour la partie 2.1. Ce score est une bonne mesure pour savoir si votre traitement est correct.

1. Justifier tous les choix de traitements que vous faites ici.


Colonne(s) | Traitement | Justification |
 :---: | :---: | :---: |
 Index | Supression | Cette variable est indépendante de income. On ne le considère pas.|
 Age | Normalisation | C'est une quantité qui doit être traduite sur une échelle continue et standard. Il est normal qu'en ayant moins d'ancienneté, ou simplement en étant un enfant, le salaire soit moins élevé. |
 Workclass | Catégorisation | Toutes les valeurs forment une catégorie car nous supposons que chaque secteur rapporte un revenu différent |
 Final Weight | Supression | Cette variable est indépendante de income. On ne la considère pas. |
 Education | Catégorisation | Quelqu'un n'ayant pas eu son diplôme à l'université aura probablement un revenu très différent de quelqu'un qui l'a complété. Pour les études universitaires, chaque échelon est une catégorie en soi parce que la compétence est liée avec le revenu. Nous regroupons donc toutes les études en dessous de HS-complete ensemble, et le reste demeure séparé.|
 Marital-Status | Catégorisation | Nous supposons que des dispositions maritales différentes dictent des revenus différents. Nous regroupons donc divorced & separated par similarité, et married-spouse-absent & windowed par similarité. Le reste demeure des catégories séparées. |
 Occupation | Catégorisation | Nous avons regroupé les types de travail qui selon nous rapportent des salaires similaires. Donc, nous avons regroupé Priv-house-serv &  Handlers-cleaners, par similarité de travail et parce que nous supposons que ce sont deux catégories qui ont des assez faibles revenus. Nous avons regroupé Machine-op-inspct & Craft-repair car ce sont des travails manuels qui tous deux rapportent de moyens revenus. Nous avons regroupé Prof-specialty & Exec-managerial car ce sont deux catégories où les salaires sont assez élevés. Finalement, nous avons regroupé Sales, Adm-clerical & Tech-support car ils se retrouvent, selon nous, dans des groupes salariaux similaires. |
 Relationship | Catégorisation |  Nous supposons que des dispositions relationelles différentes dictent des revenus différents. Nous regroupons donc Husband & Wife pour leur similarité, et Not-in-family & Unmarried également pour leur similarité. |
 Sex | Catégorisation | Les données indiquent que les deux sexes possibles sont homme ou femme. Ils sont deux catégories différentes en raison des disparités en revenu connues entre les deux sexes |
 Capital-gain | Normalisation | C'est une quantité qui doit être traduite sur une échelle continue et standard. Un gain de capital peut indiqué une hausse de revenu. |
 Capital-loss | Normalisation | C'est une quantité qui doit être traduite sur une échelle continue et standard. Il est normal qu'une perte en capital indique un revenu moins élevé, ou indique un intérêt pour les investissements qui peuvent affirmer le contraire. |
 Hours per week | Normalisation | C'est une quantité qui doit être traduite sur une échelle continue et standard. Il est plausible que le nombre d'heures de travail affecte linéairement le revenu. |
 Native country | Catégorisation | Catégorisation par régions dans le monde. Nous nous basons sur nos préjugés et la littérature pour regrouper par similarité. Nous aurons donc l'Amérique du Nord, l'Amérique du Sud et îles avoisinnantes, l'Europe et l'Asie.

### 2.2 Pipeline (3 points)
Pour faciliter le processus du traitement de données, une pipeline est utilisée. Cela permet de rapidement modifier les transformations appliquées sur l'ensemble de données.

#### Implémentation
1. Implémenter et associer vos méthodes de traitements a des pipelines.
2. Mettez tous vos pipelines dans le ColumnTransformer.

In [10]:
from sklearn.base import BaseEstimator, TransformerMixin
## Wrapper pour vous aider pour les pipelines
class TransformationWrapper(BaseEstimator,TransformerMixin):
    
    def __init__(self,fitation= None, transformation = None): 
        
        self.transformation = transformation
        self.fitation = fitation
        
    
        
    def fit(self, X, y=None):
        X = pd.DataFrame(X)
        self.data_ = None
        self.column_name_ = X.columns[0]
        if self.fitation == None:
            return self
        
        self.data_ = [self.fitation(X[self.column_name_])]
        return self  
    
    def transform(self, X, y=None): 
        X = pd.DataFrame(X)
        
        if self.data_ != None:
            return pd.DataFrame(X.apply(
                lambda row: pd.Series( self.transformation(row[self.column_name_], self.data_)),
                axis = 1
            ))
        else:
            return pd.DataFrame(X.apply(
                lambda row: pd.Series( self.transformation(row[self.column_name_])),
                axis = 1
            ))
        
        
from sklearn.preprocessing import LabelEncoder
class LabelEncoderP(LabelEncoder):
    def fit(self, X, y=None):
        super(LabelEncoderP, self).fit(X)
    def transform(self, X, y=None):
        return pd.DataFrame(super(LabelEncoderP, self).transform(X))
    def fit_transform(self, X, y=None):
        return super(LabelEncoderP, self).fit(X).transform(X)

**Déclaration des Imputer pour le remplacement des valeurs manquantes**

In [11]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

#Imputer pour les valeurs numériques
numeric_imputer = SimpleImputer(strategy='mean')


most_frequent_values = X_train.mode()

#Imputer pour les variables catégorielles
workclass_imputer = SimpleImputer(missing_values='?', strategy='constant', fill_value=most_frequent_values.loc[0, 'Workclass'])
education_imputer = SimpleImputer(missing_values='?', strategy='constant', fill_value=most_frequent_values.loc[0, 'Education'])
marital_imputer = SimpleImputer(missing_values='?', strategy='constant', fill_value=most_frequent_values.loc[0, 'Marital-status'])
occupation_imputer = SimpleImputer(missing_values='?', strategy='constant', fill_value=most_frequent_values.loc[0, 'Occupation'])
relationship_imputer = SimpleImputer(missing_values='?', strategy='constant', fill_value=most_frequent_values.loc[0, 'Relationship'])
sex_imputer = SimpleImputer(missing_values='?', strategy='constant', fill_value=most_frequent_values.loc[0, 'Sex'])
country_imputer = SimpleImputer(missing_values='?', strategy='constant', fill_value=most_frequent_values.loc[0, 'Native country'])

**Remplacement des valeurs manquantes et normalisation des variables à valeur numérique**

Pour les ensembles de test et d'entraînement

In [12]:
X_train['Age'] = numeric_imputer.fit_transform(X_train['Age'].values.reshape(-1,1))
X_train['Age'] = scaler.fit_transform(X_train['Age'].values.reshape(-1,1))
X_test['Age'] = numeric_imputer.transform(X_test['Age'].values.reshape(-1,1))
X_test['Age'] = scaler.transform(X_test['Age'].values.reshape(-1,1))

X_train['Capital-gain'] = numeric_imputer.fit_transform(X_train['Capital-gain'].values.reshape(-1,1))
X_train['Capital-gain'] = scaler.fit_transform(X_train['Capital-gain'].values.reshape(-1,1))
X_test['Capital-gain'] = numeric_imputer.transform(X_test['Capital-gain'].values.reshape(-1,1))
X_test['Capital-gain'] = scaler.transform(X_test['Capital-gain'].values.reshape(-1,1))

X_train['Capital-loss'] = numeric_imputer.fit_transform(X_train['Capital-loss'].values.reshape(-1,1))
X_train['Capital-loss'] = scaler.fit_transform(X_train['Capital-loss'].values.reshape(-1,1))
X_test['Capital-loss'] = numeric_imputer.transform(X_test['Capital-loss'].values.reshape(-1,1))
X_test['Capital-loss'] = scaler.transform(X_test['Capital-loss'].values.reshape(-1,1))

X_train['Hours per week'] = numeric_imputer.fit_transform(X_train['Hours per week'].values.reshape(-1,1))
X_train['Hours per week'] = scaler.fit_transform(X_train['Hours per week'].values.reshape(-1,1))
X_test['Hours per week'] = numeric_imputer.transform(X_test['Hours per week'].values.reshape(-1,1))
X_test['Hours per week'] = scaler.transform(X_test['Hours per week'].values.reshape(-1,1))


**Remplacement des valeurs manquantes des variables catégorielles**

Pour les ensembles de test et d'entraînement

In [13]:
categories = ['Workclass', 'Education', 'Marital-status', 'Occupation', 'Relationship', 'Sex', 'Native country']

for cat in categories:
    X_train[cat] = X_train[cat].str.strip()
    X_test[cat] = X_test[cat].str.strip()

X_train['Workclass'] = workclass_imputer.fit_transform(X_train['Workclass'].values.reshape(-1, 1))
X_test['Workclass'] = workclass_imputer.transform(X_test['Workclass'].values.reshape(-1,1))

X_train['Education'] = education_imputer.fit_transform(X_train['Education'].values.reshape(-1, 1))
X_test['Education'] = education_imputer.transform(X_test['Education'].values.reshape(-1,1))

X_train['Marital-status'] = marital_imputer.fit_transform(X_train['Marital-status'].values.reshape(-1, 1))
X_test['Marital-status'] = marital_imputer.transform(X_test['Marital-status'].values.reshape(-1,1))

X_train['Occupation'] = occupation_imputer.fit_transform(X_train['Occupation'].values.reshape(-1, 1))
X_test['Occupation'] = occupation_imputer.transform(X_test['Occupation'].values.reshape(-1,1))

X_train['Relationship'] = relationship_imputer.fit_transform(X_train['Relationship'].values.reshape(-1, 1))
X_test['Relationship'] = relationship_imputer.transform(X_test['Relationship'].values.reshape(-1,1))

X_train['Sex'] = sex_imputer.fit_transform(X_train['Sex'].values.reshape(-1, 1))
X_test['Sex'] = sex_imputer.transform(X_test['Sex'].values.reshape(-1,1))

X_train['Native country'] = country_imputer.fit_transform(X_train['Native country'].values.reshape(-1, 1))
X_test['Native country'] = country_imputer.transform(X_test['Native country'].values.reshape(-1,1))

**Déclaration des parser pour regrouper les valeurs des variables catégorielles**

In [14]:
def parse_education(text):
    if 'Preschool' in text or '1st' in text  or '5th' in text  or '7th' in text  or '9th' in text\
    or '10th' in text or '11th' in text or '11th' in text:
        return 'no-HS'
    elif 'Assoc-acdm' in text or 'Prof-school' in text  or 'Assoc-voc' in text:
        return 'Professional School'
    return text

def parse_marital(text):
    if 'Divorced' in text  or 'Sep' in text:
        return 'divsep'
    elif 'Widowed' in text or 'absent' in text in text:
        return 'abs'
    return text

def parse_relationship(text):
    if 'Husband' in text  or 'Wife' in text:
        return 'husbwife'
    elif 'Not-in-family' in text or 'Unmarried' in text in text:
        return 'single'
    return text

def parse_country(text):
    if 'United' in text or 'Canada' in text  or 'Outlying' in text:
        return 'North America'
    elif 'Pol' in text or 'Port' in text or 'Scot' in text or 'Yugo' in text or 'Ire' in text\
    or 'Italy' in text or 'Hung' in text or 'Holand' in text or 'Greece' in text:
        return 'Europe'
    elif 'Cambo' in text or 'China' in text or 'Iran' in text or 'Japan' in text or 'Laos' in text\
    or 'Hong' in text or 'Phil' in text or 'Tai' in text or 'Thai' in text or 'Viet' in text:
        return 'Asia'
    return 'South America'

def parse_occupation(text):
    if any(x in text for x in ['cleaner', 'house']):
        return 'CleanHouse'
    elif any(x in text for x in ['Machine', 'Craft']):
        return 'CraftMachine'
    elif any(x in text for x in ['Prof', 'Exec']):
        return 'ProfExec'
    elif any(x in text for x in ['Sales', 'Adm', 'Tech']):
        return 'AdmSalesTech'
    return text

def parse_income(text):
    if '>' in text:
        return 'Over'
    elif '<' in text in text:
        return 'Under'
    return text

**Application des parsers sur les variables catégorielles**

In [15]:
X_train['Marital-status'] = X_train.apply(lambda row: pd.Series(parse_marital(row['Marital-status'])), axis =1)
X_test['Marital-status'] = X_test.apply(lambda row: pd.Series(parse_marital(row['Marital-status'])), axis =1)

X_train['Native country'] = X_train.apply(lambda row: pd.Series(parse_country(row['Native country'])), axis =1)
X_test['Native country'] = X_test.apply(lambda row: pd.Series(parse_country(row['Native country'])), axis =1)

X_train['Relationship'] = X_train.apply(lambda row: pd.Series(parse_relationship(row['Relationship'])), axis =1)
X_test['Relationship'] = X_test.apply(lambda row: pd.Series(parse_relationship(row['Relationship'])), axis =1)

X_train['Education'] = X_train.apply(lambda row: pd.Series(parse_education(row['Education'])), axis =1)
X_test['Education'] = X_test.apply(lambda row: pd.Series(parse_education(row['Education'])), axis =1)

X_train['Occupation'] = X_train.apply(lambda row: pd.Series(parse_occupation(row['Occupation'])), axis =1)
X_test['Occupation'] = X_test.apply(lambda row: pd.Series(parse_occupation(row['Occupation'])), axis =1)

**Transformation des variables catégorielles en catégories numériques**

In [16]:
#Transformation des variables catégorielles en catégories numériques
labelEncoder = LabelEncoderP()

X_train['Sex'] = labelEncoder.fit_transform(X_train['Sex'].values)
X_test['Sex'] = labelEncoder.transform(X_test['Sex'].values)

X_train['Education'] = labelEncoder.fit_transform(X_train['Education'].values)
X_test['Education'] = labelEncoder.transform(X_test['Education'].values)

X_train['Workclass'] = labelEncoder.fit_transform(X_train['Workclass'].values)
X_test['Workclass'] = labelEncoder.transform(X_test['Workclass'].values)

X_train['Marital-status'] = labelEncoder.fit_transform(X_train['Marital-status'].values)
X_test['Marital-status'] = labelEncoder.transform(X_test['Marital-status'].values)

X_train['Occupation'] = labelEncoder.fit_transform(X_train['Occupation'].values)
X_test['Occupation'] = labelEncoder.transform(X_test['Occupation'].values)

X_train['Relationship'] = labelEncoder.fit_transform(X_train['Relationship'].values)
X_test['Relationship'] = labelEncoder.transform(X_test['Relationship'].values)

X_train['Native country'] = labelEncoder.fit_transform(X_train['Native country'].values)
X_test['Native country'] = labelEncoder.transform(X_test['Native country'].values)

**Encodage des variables catégorielles en One-Hot**

In [18]:
from sklearn.preprocessing import OneHotEncoder

categorical_encoder = OneHotEncoder(categories = 'auto', sparse = False)
columns = []

for cat in ["Workclass", "Education", "Marital-status", "Occupation", "Relationship", "Native country"]:
    new_columns_train = categorical_encoder.fit_transform(X_train[cat].values.reshape(-1,1))
    for col_num in range(np.shape(new_columns_train)[1]):
        columns.append(cat+str(col_num))
    X_train = X_train.drop(columns=[cat])
    X_train = pd.concat([X_train,pd.DataFrame(new_columns_train, columns=columns)], axis = 1)

    new_columns_test = categorical_encoder.transform(X_test[cat].values.reshape(-1,1))
    X_test = X_test.drop(columns=[cat])
    X_test = pd.concat([X_test,pd.DataFrame(new_columns_test, columns=columns)], axis = 1)
    columns = []
    

index       Age  Final weight  Sex  Capital-gain  Capital-loss  \
0   7762 -1.500012      423024.0    1     -0.146117     -0.218564   
1  23881 -1.572782      178953.0    0     -0.146117     -0.218564   
2  30507 -0.990623      348986.0    1     -0.146117     -0.218564   
3  28911 -1.354473      218215.0    0     -0.146117     -0.218564   
4  19484  0.610315      244025.0    1     -0.146117     -0.218564   

   Hours per week  Workclass0  Workclass1  Workclass2  ...  Occupation7  \
0       -1.641450         0.0         0.0         0.0  ...          0.0   
1       -1.641450         0.0         0.0         0.0  ...          0.0   
2       -0.030764         0.0         0.0         1.0  ...          0.0   
3       -0.836107         0.0         0.0         0.0  ...          0.0   
4        1.257786         0.0         0.0         0.0  ...          0.0   

   Occupation8  Relationship0  Relationship1  Relationship2  Relationship3  \
0          0.0            0.0            0.0            0.0            1.0   
1          0.0            0.0            1.0            0.0            0.0   
2          0.0            1.0            0.0            0.0            0.0   
3          0.0            0.0            1.0            0.0            0.0   
4          0.0            0.0            0.0            0.0            1.0   

   Native country0  Native country1  Native country2  Native country3  
0              0.0              0.0              1.0              0.0  
1              0.0              0.0              1.0              0.0  
2              0.0              0.0              1.0              0.0  
3              0.0              0.0              1.0              0.0  
4              0.0              0.0              0.0              1.0  

[5 rows x 46 columns]

**Élimination des colonnes de Final Weight et index pour les X**

In [19]:
X_train = X_train.drop(columns=['Final weight', 'index'])
X_test_preprocess = X_test.drop(columns=['Final weight', 'index']) #Il faut garder les index dans X_test pour la soumission

# 3. Model selection (2 points)

Encodage de la classe cible sous forme d'entiers pour l'utiliser
avec les algorithmes de scikit-learn. Vous devez avoir 2 classes.

In [20]:
from sklearn.preprocessing import LabelEncoder

target_label = LabelEncoder()
y_train = X_train.apply(lambda row: pd.Series(parse_income(row['Income'])), axis =1)
y_train_label = target_label.fit_transform(y_train)

C:\Users\maude\.julia\conda\3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## 3.1 Ensemble de validation (0.5 point)
Pour comparer différents modèles entre eux, on ne peut pas utiliser
l'ensemble de test, sinon on serait tenté de garder le modèle correspondant le mieux à l'ensemble de test ce qui pourrait conduire à l'overfitting.

Il est d'usage de créer un nouvel ensemble de la taille de l'ensemble de test, l'ensemble de **validation**.

###  Cross-validation

La cross-validation est une méthode utile pour comparer la performance de différents modèles de machine learning **sans créer d'ensemble de validation**.

Il existe différents types de cross-validation, la procédure la plus classique est la suivante:
* Diviser aléatoirement l'ensemble d'entraînement en deux parties (90%/10% par exemple).
* Entraîner le modèle sur la plus grande partie, et le tester sur l'autre partie.
* Recommencer n fois
* Calculer la moyenne et l'écart type des résultats

Les avantages sont les suivants:
* Considérer la totalité de l'ensemble d'entraînement pour l'évaluation (sans se priver de l'ensemble de validation)
* Obtenir l'écart-type des résultats permet une meilleure évaluation de la précision du modèle.

L'inconvénient principal est le temps de calcul, étant donné que l'on effectue l'apprentissage du modèle plusieurs fois, cette méthode peut être impossible pour des datasets contenant un grand nombre d'exemple (> 10e5)

### Implémentation
1. Implémenter la fonction `compare()`. Cette fonction effectue la crossvalidation pour différents modèles et retourne la moyenne et l'écart-type des métriques pour chaque modèle.



In [21]:
from sklearn.model_selection import cross_validate, train_test_split

def compare(models,X_train,y_train,nb_runs,scoring):
    scores = []
    for m in models:
        scores.append(cross_validate(m, X_train, y_train, cv=nb_runs, scoring=scoring))
            
    return scores

## 3.2 Essai de modèle de sklearn (0.5 point)


**Choisir au moins deux modèles permettant la classification binaire sur sklearn en plus du modèle implémenté dans la première partie du TP**.

**En vous basant sur les différentes métriques retournées par la fonction `compare()`, concluez quant au modèle le plus performant.**

Evaluez les modèles pour les différentes métriques proposées:
* **log loss**: c'est la métrique d'évaluation de kaggle
* **precision**: correspond à la qualité de la prédiction, le nombre de classes correctement prédites par le nombre de prédiction total
* **recall**: le nombre d'éléments appartenant à une classe, identifiés comme tel, divisé par le nombre total des éléments de cette classe.
* **f-score**: une moyenne de la precision et du recall

**Remarque: precision et recall sont deux mesures complémentaires pour l'évaluation d'un modèle de classification.**

Dans le cas d'une classification binaire avec un déséquilibre de la classe cible important, (90%/10%), en évaluant le résultat de la classification avec l'accuracy (nombre de prédictions correctes divisé par le nombre de prédictions total), on peut obtenir un très bon score (90% d'accuracy) en choisissant de prédire systématiquement la classe majoritaire.

Dans un tel cas, la precision serait élevée de même, mais le recall serait très bas , nous indiquant la médiocrité de notre modèle.


In [30]:
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

nb_run = 3

X_train_preprocess = X_train.drop(columns=['Income'])

models = [
    SoftmaxClassifier(), # le modele que vous avez implémenté plus haut
    DecisionTreeClassifier(max_depth=15),
    RandomForestClassifier(max_depth=15, n_estimators=75),
]

scoring = ['neg_log_loss', 'precision_macro','recall_macro','f1_macro']

scores = compare(models,X_train_preprocess,y_train_label,nb_run, scoring)

print("Résultats du SoftmaxClassifier: \n")
print(scores[0])

print("\n\nRésultats du DecisionTreeClassifier: \n")
print(scores[1])

print("\n\nRésultats du RandomForestClassifier: \n")
print(scores[2])

Résultats du SoftmaxClassifier: 

{'fit_time': array([1.48885012, 0.42980242, 4.76274323]), 'score_time': array([0.04886317, 0.04886293, 0.04884505]), 'test_neg_log_loss': array([ -9.40083663, -12.99429277,  -9.14646494]), 'test_precision_macro': array([0.71979808, 0.50290372, 0.77078227]), 'test_recall_macro': array([0.56513955, 0.50164373, 0.50369174]), 'test_f1_macro': array([0.56147101, 0.48935001, 0.44092408])}


Résultats du DecisionTreeClassifier: 

{'fit_time': array([0.19545579, 0.16155195, 0.15756273]), 'score_time': array([0.0538497 , 0.06681037, 0.05285287]), 'test_neg_log_loss': array([-1.58762849, -1.54117349, -1.72075037]), 'test_precision_macro': array([0.80194911, 0.79392349, 0.78621884]), 'test_recall_macro': array([0.77423004, 0.76805643, 0.77096545]), 'test_f1_macro': array([0.78640074, 0.77946192, 0.77803431])}


Résultats du RandomForestClassifier: 

{'fit_time': array([1.47788   , 1.53073382, 1.51577544]), 'score_time': array([0.72996354, 0.70802569, 0.69506097])

**Justification pour le meilleur modèle**

Le meilleur des trois modèles est le RandomForestClassifier car c'est lui qui donne les meilleurs scores F1 et qui a la meilleure précision. Sa performance en termes de recall est similaire à celle du DecisionTreeClassifier, mais puisque ses résultats sont meilleurs pour les deux autres indicateurs, c'est lui que nous choisissons.


## 3.3 Matrice de confusion (0.5 point)

La matrice de confusion A est telle que $A_{i,j}$ correspond au nombre d'exemples de la classe i classifié comme appartenant à la classe j.

Entrainez le modèle sélectionné sur la totalité de l'ensemble d'entraînement.
A l'aide de la matrice de confusion et de la distribution des classes, analysez plus en détail les performances du modèle choisi et **justifiez** les.

In [31]:
# Train selected model
selected_model = RandomForestClassifier(max_depth=15, n_estimators=75)
selected_model = selected_model.fit(X_train_preprocess,y_train_label)
y_pred = selected_model.predict(X_train_preprocess)

###### Matrice de confusion

In [32]:
from sklearn.metrics import confusion_matrix
pd.DataFrame(confusion_matrix(y_train_label, y_pred), columns = target_label.classes_, index = target_label.classes_)

Over  Under
Over   5088   2686
Under  1025  23924

###### Distribution des classes

In [33]:
import matplotlib.pyplot as plt 
print(target_label.classes_)
pd.Series(y_train_label).hist()

['Over' 'Under']


**Justification avec la matrice de confusion et la distribution des classes**

Il y a beacoup plus d'exemples de notre échantillon d'entraînement qui font partie de la classe "<=50K" (environ 25 000) comparé à ceux faisant partie de la classe ">50K". Il est donc normal que notre modèle apprenne plus et mieux pour cette première classe que pour la deuxième, ce qui explique la différence de performance. En effet, le modèle fait plus de 15% de mauvaises prédictions et environ 85% de bonnes prédictions pour la classe ">50K" et environ 10% de mauvaises prédictions et environ 90% de bonnes prédictions pour la classe "<=50K"

## 3.4 Soumission (0.5 point)

Enfin, effectuez la prédiction sur l'ensemble de test et joignez les résultats au rendu du TP. Vous devez soumettre vos résultats sur kaggle. Vous pouvez choisir jusqu'à deux modèles. Par défaut, les deux dernières soumissions sont prises. La justification (les section 3.2 et 3.3) sont seulement demandée pour le meilleur modèle selon vous.

**ATTENTION:** N'oubliez pas de respecter le format du fichier de soumission. En cas d'erreur, Kaggle score 0.0 pour la soumission.

In [34]:
def parse_income_50K(text):
    if text == 1:
        return '<=50K'
    elif text == 0:
        return '>50K'

In [35]:
X_test_preprocess
best_model_1 = selected_model
pred_test = pd.DataFrame()
pred_test['index'] = X_test['index']
pred_test['Income'] = pd.Series(best_model_1.predict(X_test_preprocess))
pred_test['Income'] = pred_test.apply(lambda row: pd.Series(parse_income_50K(row['Income'])), axis =1)

In [36]:
pred_test.to_csv("test_prediction_1.csv",index = False)